export const tr: string[] = [
    "Sağlam bir el sıkışma yapın",
    "İnsanlara göz teması kurun",
    "Duşta şarkı söyleyin",
    "Harika bir stereo sisteminiz olsun",
    "Bir kavga halindeyseniz, ilk vuruşu yapın ve sert vurun",
    "Sırları saklayın",
    "Hiç kimseyi vazgeçirmeyin. Mucizeler her gün olur. (No.17'ye bakınız)",
    "Her zaman uzanmış bir eli kabul edin",
    "Cesur olun. Eğer değilseniz bile, öyleymiş gibi davranın. Kimse farkı anlayamaz.",
    "Islık çalın",
    "Alaycı yorumlardan kaçının",
    "Hayat arkadaşınızı dikkatlice seçin. Bu karardan yaşamınızın yüzde 90'ı mutluluğunuz veya mutsuzluğunuz gelecektir.",
    "Kimseye bir daha öğrenemeyeceğiniz kitaplar ödünç vermeyin",
    "Kimseyi umutsuzluğa düşürmeyin; belki de sahip oldukları tek şey budur",
    "Çocuklarla oyun oynarken, onların kazanmasına izin verin",
    "İnsanlara ikinci bir şans verin, ama üçüncüsünü verin",
    "Romantik olun",
    "Tanıdığınız en pozitif ve coşkulu kişi olun",
    "Rahatlayın. Gevşeyin. Nadir hayati ve ölümle ilgili meseleler dışında, hiçbir şey ilk başta göründüğü kadar önemli değil.",
    "Telefonun önemli anları kesintiye uğratmasına izin vermeyin. Arayanın değil, bizim için orada.",
    "İyi bir kaybedici olun",
    "İyi bir kazanan olun",
    "Bir arkadaşınızı bir sırla yüklemekten önce iki kez düşünün",
    "Birisi sizi kucakladığında, onların ilk bırakma izin verin",
    "Mütevazı olun. Sen doğmadan önce birçok şey başarıldı.",
    "Basit tutun",
    "Hiçbir şeyi kaybetmeyen kişiden kaçının",
    "Köprüleri yakmayın. Aynı nehrin birçok kez geçmenize şaşıracaksınız.",
    "Hayatınızı 'Pişmanlık Yok' olarak okuyun",
    "Cesur ve cesur olun. Hayatta geriye dönüp baktığınızda, yapmadıklarınızı yaptıklarınızdan daha çok pişman olacaksınız.",
    "Birisine seni sevdiğini söyleme fırsatını asla kaçırma",
    "Unutma ki hiç kimse yalnız başına başarılı olmaz. Minnettar bir kalbe sahip olun ve size yardım edenleri hızlı bir şekilde tanıyın.",
    "Tavrınızı kontrol edin. Başkasının onu sizin için seçmesine izin vermeyin.",
    "Arkadaşlarınızı ve akrabalarınızı hastanede ziyaret edin; sadece birkaç dakika kalmalısınız",
    "Her gün favori müziğinizle başlayın",
    "Ara sıra manzaralı yolu tercih edin",
    "Birçok Sevgililer Günü kartı gönderin. Onlara 'Seni harika bulan biri' olarak imzalayın.",
    "Telefona enerji ve coşkuyla cevap verin.",
    "Yatak başı masanızda bir not defteri ve kalem bulundurun. Milyon dolarlık fikirler bazen saat 03:00'te gelir.",
    "Yaşamı kazanmak için çalışan herkese saygı gösterin, işleri ne kadar önemsiz olursa olsun",
    "Sevdiklerinize çiçek gönderin. Nedenini sonra düşünün.",
    "Birinin gününü onlar için yol ücretini ödeyerek geçirin",
    "Birinin kahramanı olun",
    "Sadece aşk için evlenin.",
    "Şükranlarınızı sayın.",
    "Birinin evinde misafirseniz yemeği övün.",
    "Bir okul otobüsündeki çocuklara el sallayın.",
    "Herhangi bir işte başarının yüzde 80'i insanlarla başa çıkma yeteneğinize dayanır.",
    "Hayatın adil olmasını beklemeyin.",
  ];
  