export const advices: string[] = [
  "Serrez la main fermement",
  "Regardez les gens dans les yeux",
  "Chantez sous la douche",
  "Possédez un bon système stéréo",
  "Si vous êtes dans une bagarre, frappez d'abord et frappez fort",
  "Gardez des secrets",
  "Ne jamais abandonner personne. Des miracles se produisent tous les jours. (Voir le n°17)",
  "Acceptez toujours une main tendue",
  "Soyez courageux. Même si vous ne l'êtes pas, faites semblant de l'être. Personne ne peut faire la différence.",
  "Sifflez",
  "Évitez les remarques sarcastiques",
  "Choisissez votre partenaire de vie avec soin. De cette décision découlera 90 % de votre bonheur ou de votre misère.",
  "Faites-en une habitude de faire des choses gentilles pour des personnes qui ne le sauront jamais",
  "Ne prêtez que les livres que vous ne souhaitez jamais revoir",
  "Ne privez jamais quelqu'un d'espoir ; cela pourrait être tout ce qu'il a",
  "Lorsque vous jouez avec des enfants, laissez-les gagner",
  "Donnez une deuxième chance aux gens, mais pas une troisième",
  "Soyez romantique",
  "Devenez la personne la plus positive et enthousiaste que vous connaissez",
  "Détendez-vous. Relaxez-vous. Sauf pour des situations rares de vie ou de mort, rien n'est aussi important qu'il n'y paraît au départ.",
  "Ne laissez pas le téléphone interrompre les moments importants. Il est là pour notre commodité, pas pour celle de l'appelant.",
  "Soyez un bon perdant",
  "Soyez un bon gagnant",
  "Réfléchissez à deux fois avant de confier un secret à un ami",
  "Lorsque quelqu'un vous serre dans ses bras, laissez-le être le premier à lâcher prise",
  "Soyez modeste. Beaucoup de choses ont été accomplies avant votre naissance.",
  "Simplifiez les choses",
  "Méfiez-vous de la personne qui n'a rien à perdre",
  "Ne brûlez pas les ponts. Vous serez surpris du nombre de fois où vous devrez traverser le même fleuve.",
  "Vivez votre vie de sorte que votre épitaphe puisse dire, « Sans Regrets »",
  "Soyez audacieux et courageux. Quand vous regarderez en arrière sur la vie, vous regretterez plus les choses que vous n'avez pas faites que celles que vous avez faites.",
  "Ne gaspillez jamais une occasion de dire à quelqu'un que vous l'aimez",
  "Rappelez-vous que personne n'y parvient seul. Ayez un cœur reconnaissant et soyez prompt à reconnaître ceux qui vous ont aidé.",
  "Prenez le contrôle de votre attitude. Ne laissez pas quelqu'un d'autre la choisir pour vous.",
  "Rendez visite à des amis et à des proches lorsqu'ils sont à l'hôpital ; vous n'avez besoin que de rester quelques minutes",
  "Commencez chaque jour avec un peu de votre musique préférée",
  "De temps en temps, prenez le chemin pittoresque",
  "Envoyez beaucoup de cartes de Saint-Valentin. Signez-les, « Quelqu'un qui pense que vous êtes formidable. »",
  "Répondez au téléphone avec enthousiasme et énergie dans votre voix.",
  "Gardez un bloc-notes et un crayon sur votre table de chevet. Des idées valant des millions de dollars peuvent parfois survenir à 3 heures du matin.",
  "Montrez du respect pour tous ceux qui travaillent pour gagner leur vie, peu importe la trivialité de leur travail",
  "Envoyez des fleurs à vos proches. Trouvez une raison plus tard.",
  "Faites la journée de quelqu'un en payant le péage pour la personne dans la voiture derrière vous",
  "Devenez le héros de quelqu'un",
  "Ne vous mariez que par amour.",
  "Comptez vos bénédictions.",
  "Faites des compliments sur le repas lorsque vous êtes invité chez quelqu'un.",
  "Faites signe aux enfants dans un bus scolaire.",
  "Rappelez-vous que 80 % du succès dans n'importe quel emploi est basé sur votre capacité à traiter avec les gens.",
  "Ne vous attendez pas à ce que la vie soit juste.",
];
